version: '3'

volumes:
  
services:
  nginx:
    image:
    restart: always
    ports: 80:80
    networks:
      - 
    volumes:
      -
  python1:
    build: .
    ports: 5000:5000
    restart: always
    networks:
      -
    volumes:
      -
    environment:
      SERVICE: serviço A

  python2:
    build: .
    ports: 5000:5000
    restart: always
    networks:
      -
    volumes:
      -
    environment:
      SERVICE: serviço B
